M48
; DRILL file {KiCad (6.0.8)} date Wed May 31 19:07:21 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-31T19:07:21+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X4.7008Y-4.1142
X4.7008Y-4.7441
X5.6063Y-4.1142
X5.6063Y-4.7441
T0
M30
